package com.filocha.hibernate;

import com.filocha.server.ParkingResponseModel;

/**
 * Defines methods to manage parking operations
 *
 */
public interface ParkingService {
	/**
	 * Fetches information about parking from database
	 * 
	 * @param parkingName
	 *            parking name
	 * @param userEmail
	 *            user email
	 * @return parking model with information about parking
	 */
	ParkingResponseModel getParkingInfo(String parkingName, String userEmail);

	/**
	 * Tries to reserve a parking place for a user
	 * 
	 * @param userEmail
	 *            user email
	 * @param parkingName
	 *            parking name
	 * @return true if reservation was suscessful, otherwise false
	 */
	boolean reserveParkingPlace(String userEmail, String parkingName);

	/**
	 * Tries to unsubscribe user from his parking place
	 * 
	 * @param userEmail
	 *            user email
	 * @return true if unsubscribe was sucsessful, otherwise false
	 */
	boolean leaveParkingPlace(String userEmail);

	/**
	 * This method is for testing usage only, it adds new parking to database
	 *
	 * The model should already contain id set to unique value, because id is
	 * not generated by database.
	 * 
	 * @param model
	 *            model
	 * @return newly created model.
	 */
	ParkingModel addNewParking(ParkingModel model);

	/**
	 * This method is for testing usage only, it delete values for given table
	 * name
	 * 
	 * @param modelClassName
	 *            name of table in database
	 */
	public Void clearTableValues(String modelClassName);
}
